!function(o){"use strict";function a(a){a.each(function(){var a=o(this),s=a.data("delay"),i="animated "+a.data("animation");a.css({"animation-delay":s,"-webkit-animation-delay":s}),a.addClass(i).one("webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend",function(){a.removeClass(i)})})}o(document).ready(function(){o('.scrolling  a[href*="#"], .scrolling .btn-scroll-down').on("click",function(a){a.preventDefault(),a.stopPropagation();var s=o(this).attr("href");o(window).width()<767?o(s).velocity("scroll",{duration:800,offset:-70,easing:"easeOutExpo",mobileHA:!1}):o(window).width()>=768&&o(s).velocity("scroll",{duration:800,offset:-88,easing:"easeOutExpo",mobileHA:!1})})}),o(window).on("load",function(){var a=o(".header"),s=a.find(".navbar"),i=0,n=o(".navbar-sticky");o(window).scroll(function(){var e=o(this).scrollTop();e>i?n.addClass("navbar-scrollUp"):n.removeClass("navbar-scrollUp"),i=e,s.hasClass("navbar-sticky")&&(o(this).scrollTop()<=600||o(this).width()<=300)?(s.removeClass("navbar-sticky").appendTo(a),a.css("height","auto")):!s.hasClass("navbar-sticky")&&o(this).width()>300&&o(this).scrollTop()>600&&(a.css("height",a.height()),s.addClass("navbar-scrollUp"),s.css({opacity:"0"}).addClass("navbar-sticky"),s.appendTo(o("body")).animate({opacity:1}))}),o(window).width()<750&&o(".navbar-nav.site_nav .nav-item .nav-link").on("click",function(){o(".navbar-collapse.collapse").removeClass("show")}),o(window).trigger("resize"),o(window).trigger("scroll")}),o("#banner-style-one").on("init",function(s,i){a(o(".slide1").find("[data-animation]"))}),o("#banner-style-one").on("beforeChange",function(s,i,n,e){a(o('div.slide[data-slick-index="'+e+'"]').find("[data-animation]"))}),o("#banner-style-one").slick({autoplay:!0,slidesToScroll:!0,arrows:!1,dots:!0,autoplaySpeed:5e3,speed:600,fade:!0}),o(".testimonial-carouel").slick({autoplay:!0,slidesToShow:1,slidesToScroll:1,autoplaySpeed:5e3,speed:1e3}),o(".product-slider").slick({autoplay:!0,slidesToShow:3,slidesToScroll:3,arrows:!1,dots:!0,centerPadding:"100px",autoplaySpeed:5e3,speed:1e3,responsive:[{breakpoint:1024,settings:{slidesToShow:3,slidesToScroll:3,infinite:!0,dots:!1}},{breakpoint:992,settings:{slidesToShow:2,slidesToScroll:2,infinite:!0,dots:!1}},{breakpoint:768,settings:{dots:!1,arrows:!1,slidesToShow:2,slidesToScroll:2}},{breakpoint:480,settings:{slidesToShow:1,slidesToScroll:1,arrows:!1,dots:!1,autoplaySpeed:3e3}}]}),o(function(){o(".feature-tabs").on("mouseenter.bs.tab.data-api",'[data-toggle="tab"]',function(){o(this).tab("show")})}),(new WOW).init(),o("body").scrollspy({target:"#navbarContent",spy:"scroll",offset:130})}(jQuery);

//============================== Google Analytics =========================
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-71155940-16', 'auto');
ga('send', 'pageview');

//============================== getsitecontrol =========================
(function (w,i,d,g,e,t,s) {w[d] = w[d]||[];t= i.createElement(g);
  t.async=1;t.src=e;s=i.getElementsByTagName(g)[0];s.parentNode.insertBefore(t, s);
})(window, document, '_gscq','script','//widgets.getsitecontrol.com/46851/script.js');
